version: "3"

services:
  knocker-lambda-api:
    build:
      context: ./knocker-lambda-api/
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./knocker-lambda-api/:/app
  # here could be the other applications
