version: "3"

services:
  knocker:
    build:
      context: ./knocker/
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./knocker/:/app
  # here could be the other applications
