version: 0.2

env:
  variables:
    STAGE: $STAGE

phases:
  install:
    commands:
      - cd knocker-lambda-api
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage $STAGE
